apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  #namespace: mysql
spec:
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
  serviceName: "mysql"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mysql # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - env:
        # see https://hub.docker.com/r/library/mysql/
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "mydb"
        - name: MYSQL_USER
          value: "mysql"
        - name: MYSQL_PASSWORD
          value: "password"
        name: mysql
        image: mysql:latest
        imagePullPolicy: Always # IfNotPresent
        ports:
        - containerPort: 3306
          name: mysql
