apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  type: NodePort
  ports:
  - name: mysql-port
    port: 3306
    nodePort: 30306
    targetPort: 3306
  selector:
    app: mysql
