apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  type: NodePort
  ports:
  - name: postgres-port
    port: 5432
    nodePort: 30432
    targetPort: 5432
  selector:
    app: postgres
